### PR TITLE
Update LTS

### PR DESCRIPTION
**Pull request by AlexeyRaga**
## Changes
- Updated LTS
- Added linter config to propagate warnings the way VSCode shows them
- Fix local docker mount folder
- Added extensions and warnings, including ones that are safe but were not good enough for `geo-naic-asn` for a broader discussion.

### CODE REVIEW

**Comment by newhoggy** [comment]
💯

**Comment by Kheldar** [comment]
The points I was making on the other PR apply equally. I don't think things like `GADTs` and `DataKinds` should be enabled by default, at least until you've put in the effort to educate the rest of the team on what they do and how they're used.

**Comment by AlexeyRaga** [comment]
My point is that they don't do anything unless you start writing ADTs in generalised way. At _that_ point it may require explanation etc. Whether you include it to the top of the file _at that point_ or not doesn't matter, does it?
The fact that the extension is enabled doesn't change anything.

**Comment by Kheldar** [comment]
It matters because by including it at the top of the file, I at least have some sort of discoverability where things are coming from.

**Comment by Kheldar** [comment]
It's not about whether *I'm* using it. Obviously I'm not going to personally use something I don't understand. It matters if *you* start using it, and I have no way of working out what the hell you're doing. Because you may leave, or get hit by a bus, or .... etc.

**Comment by newhoggy** [comment]
Probably okay to leave out those particular two since we don't use it much yet.  We can add it later.

**Comment by AlexeyRaga** [comment]
When there is a feature in the language that someone can use _accidentally_ and damage something - that feature should be disabled. Or if a feature changes the default behaviour (like `ApplicativeDo`) - don't want it enabled by default.

**Comment by Kheldar** [comment]
At the top of the file means
- I can be reasonably certain that extension is being used in that file, because my linter is going to complain if it isn't.
- I have a list of _what_ extensions are being used in a file, which means I can Google. Or to put it another way, I'm not blocked on whether you're available to talk to.

vs Globally enabled
- I don't know which files particular extensions are used in
- I don't know if a particular extension is even used
- If I see syntax I don't recognise, I have no way of knowing which extension it's coming from.

For some syntax extensions - e.g. bang-patterns, lambda-case - that's relatively benign. I don't think it's benign for the one's I mentioned.

**Comment by Kheldar** [comment]
Can you also take out `Functional Dependencies`, for the same reason.

**Comment by AlexeyRaga** [comment]
It is not a type-level stuff, it is "normal" Haskell. The reader monad uses it.
image

**Comment by AlexeyRaga** [comment]
OK, I'll remove it anyway

**Comment by Kheldar** [comment]
Thank you :) 👍

**Pull request merged**
